In [1]:
import numpy as np

# Set the size of the random matrix
matrix_size = 5

# Generate a random matrix
random_matrix = np.random.rand(matrix_size, matrix_size)

# Compute the eigendecomposition
eigenvalues, eigenvectors = np.linalg.eig(random_matrix)

# Print the original matrix
print("Random Matrix:")
print(random_matrix)

# Print the eigenvalues
print("\nEigenvalues:")
for i, eigenvalue in enumerate(eigenvalues):
    print(f"Eigenvalue {i+1}: {eigenvalue}")

# Print the eigenvectors
print("\nEigenvectors:")
for i, eigenvector in enumerate(eigenvectors.T):
    print(f"Eigenvector {i+1}: {eigenvector}")

Random Matrix:
[[0.91077325 0.05127855 0.13687059 0.20098364 0.23522137]
 [0.35898991 0.22410794 0.74015765 0.82356632 0.15964835]
 [0.5391696  0.36608487 0.98188205 0.65256585 0.09039381]
 [0.27287117 0.81573116 0.23237253 0.10668894 0.66544099]
 [0.64282776 0.77592612 0.81962734 0.21489333 0.36606427]]

Eigenvalues:
Eigenvalue 1: (2.2175025115163662+0j)
Eigenvalue 2: (0.7273648794306453+0j)
Eigenvalue 3: (-0.18990858967334429+0.1769818667024155j)
Eigenvalue 4: (-0.18990858967334429-0.1769818667024155j)
Eigenvalue 5: (0.02446624292695263+0j)

Eigenvectors:
Eigenvector 1: [0.23539109+0.j 0.45246311+0.j 0.50522906+0.j 0.43279683+0.j
 0.54525101+0.j]
Eigenvector 2: [ 0.81430747+0.j -0.37954711+0.j -0.23729262+0.j -0.35158033+0.j
 -0.11371376+0.j]
Eigenvector 3: [ 0.16120534-0.00561968j  0.54120082-0.07835745j -0.12135655-0.15882274j
 -0.07411836+0.30088079j -0.73414452+0.j        ]
Eigenvector 4: [ 0.16120534+0.00561968j  0.54120082+0.07835745j -0.12135655+0.15882274j
 -0.07411836-0.3008

In [2]:
b = np.random.rand(matrix_size, 1)

for i in range(100):
    Aib = random_matrix @ b
    norm = np.linalg.norm(Aib)
    b = Aib / norm

print(b)

[[0.23539109]
 [0.45246311]
 [0.50522906]
 [0.43279683]
 [0.54525101]]
